# Generated by Django 4.2.7 on 2023-11-08 09:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_trip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='driver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trips_offered', to='api.driver'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='passengers',
            field=models.ManyToManyField(null=True, related_name='trips_booked', to=settings.AUTH_USER_MODEL),
        ),
    ]
