# Generated by Django 4.2.7 on 2023-11-08 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_driver_driver_license_alter_driver_national_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='email',
        ),
    ]
